[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'chromium', 'xvfb-run']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build] 
cmds = ['echo "Build phase complete"']

[start]
cmd = 'xvfb-run -a python perplexity_railway.py'