[phases.setup]
nixPkgs = ['python312', 'chromium', 'xvfb-run']

[phases.install]
cmds = [
  'pip install --upgrade pip setuptools',
  'pip install selenium>=4.30.0',
  'pip install undetected-chromedriver>=3.5.0', 
  'pip install requests>=2.30.0'
]

[phases.build] 
cmds = ['echo "Build phase complete"']

[start]
cmd = 'xvfb-run -a python perplexity_railway.py'