[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python perplexity_simple.py'